/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;
using OutSystems.HubEdition.Extensibility.Data;

namespace OutSystems.HubEdition.DatabaseProvider.Cache {

    /// <summary>
    /// Base implementation of a class to represent a set of properties that are specific to a database provider.
    /// </summary>
    public class CacheProviderProperties : BaseProviderProperties {

        /// <summary>
        /// Initializes a new instance of the <see cref="CacheProviderProperties"/> class.
        /// </summary>
        /// <param name="provider">The database provider.</param>
        public CacheProviderProperties(IDatabaseProvider provider) : base(provider) { }

        /// <summary>
        /// Gets the friendly name of the database provider
        /// </summary>
        public override string DisplayName {
            get { return "Caché"; }
        }

        /// <summary>
        /// Indicates if the provider's driver supports more than one active result set for a single connection.
        /// </summary>
        /// <value>
        /// True if it supports multiple active result sets for a single connection, False otherwise.
        /// </value>
        public override bool SupportsMultipleActiveResultSets {
            get { return false; }
        }
    }
}
