/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using OutSystems.HubEdition.Extensibility.Data.DatabaseObjects;

namespace OutSystems.HubEdition.DatabaseProvider.Cache.Introspection {
    
    /// <summary>
    /// Contains information about a table source column.
    /// </summary>
    public class CacheTableSourceColumnInfo : ITableSourceColumnInfo {

        /// <summary>
        /// Initializes a new instance of the <see cref="CacheTableSourceColumnInfo"/> class.
        /// </summary>
        /// <param name="tableSource">The table source.</param>
        /// <param name="name">The name.</param>
        /// <param name="dataType">Type of the data.</param>
        /// <param name="isMandatory">if set to <c>true</c> [is mandatory].</param>
        /// <param name="isPrimaryKey">if set to <c>true</c> [is primary key].</param>
        /// <param name="isAutoGenerated">if set to <c>true</c> [is automatic generated].</param>
        public CacheTableSourceColumnInfo(ITableSourceInfo tableSource, string name, IDataTypeInfo dataType, bool isMandatory, bool isPrimaryKey, bool isAutoGenerated) {
            TableSource = tableSource;
            Name = name;
            DataType = dataType;
            IsMandatory = isMandatory;
            IsPrimaryKey = isPrimaryKey;
            IsAutoGenerated = isAutoGenerated;
        }

        /// <summary>
        /// Table source that owns the column.
        /// </summary>
        public ITableSourceInfo TableSource { get; private set; }

        /// <summary>
        /// Name that identifies the column.
        /// </summary>
        public string Name { get; private set; }

        /// <summary>
        /// Data type of the values stored in the column.
        /// </summary>
        public virtual IDataTypeInfo DataType { get; private set; }

        /// <summary>
        /// Returns true if the column must have a value assigned to it (NOT NULL), or false if it is nullable.
        /// </summary>
        public bool IsMandatory { get; private set; }

        /// <summary>
        /// Returns true if the column is part of the table source's primary key, or false otherwise.
        /// </summary>
        public bool IsPrimaryKey { get; private set; }

        /// <summary>
        /// Returns true if the column value is generated automatically when a row is inserted (e.g. sequential numbers).
        /// </summary>
        public bool IsAutoGenerated { get; private set; }

        public bool IsUnsigned { get; private set; }

    }
}
