/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;
using System.Collections.Generic;
using OutSystems.HubEdition.Extensibility.Data.DMLService;
using OutSystems.HubEdition.Extensibility.Data.DMLService.DMLPlaceholders;

namespace OutSystems.HubEdition.DatabaseProvider.Cache.DML {

    /// <summary>
    /// Defines a contract for generating DML fragments required by applications to perform specific queries (e.g. count query)
    /// </summary>
    public class CacheDMLQueries : BaseDMLQueries {

        /// <summary>
        /// Initializes a new instance of the <see cref="CacheDMLQueries"/> class.
        /// </summary>
        /// <param name="dmlService">The DML service.</param>
        internal CacheDMLQueries(IDMLService dmlService) : base(dmlService) { }

        /// <summary>
        /// Returns the DML expressions to be inserted in the <code>SELECT</code> statement of a query
        /// to limit the number of records returned.
        /// </summary>
        /// <param name="maxRecordsParam"></param>
        /// <returns>
        /// An <see cref="T:System.Collections.Generic.IDictionary`2" /> with the DML expressions.
        /// </returns>
        public override IDictionary<SelectPlaceholder, string> SQLPlaceholderValuesForMaxRecords(string maxRecordsParam) {
            Dictionary<SelectPlaceholder, string> maxRecordsStatement = new Dictionary<SelectPlaceholder, string>();
            maxRecordsStatement.Add(SelectPlaceholder.AfterSelectKeyword, " TOP " + maxRecordsParam);
            return maxRecordsStatement;
        }
    }
}
