/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System.Collections.Generic;
using OutSystems.HubEdition.Extensibility.Data.DatabaseObjects;
using OutSystems.HubEdition.Extensibility.Data.DMLService;
using OutSystems.HubEdition.Extensibility.Data.DMLService.DMLPlaceholders;

namespace OutSystems.HubEdition.DatabaseProvider.Cache.DML {

    /// <summary>
    /// Class that represents the different kinds of entity actions supported by the platform.
    /// </summary>
    public class CacheDMLEntityActions : BaseDMLEntityActions {

        /// <summary>
        /// Initializes a new instance of the <see cref="CacheDMLEntityActions"/> class.
        /// </summary>
        /// <param name="dmlService">The DML service.</param>
        /// <param name="tableSourceInfo">The table source information.</param>
        internal CacheDMLEntityActions(IDMLService dmlService, ITableSourceInfo tableSourceInfo) : base(dmlService, tableSourceInfo) { }

        private volatile IDictionary<InsertPlaceholder, string> createAndRetrieveIdPlaceholderValues;

        public override IDictionary<InsertPlaceholder, string> SQLPlaceholderValuesForCreateAndRetrieveId(string idColumnName, string outputParameterName, out RetrieveIdMethod retrieveIdMethod) {
            retrieveIdMethod = RetrieveIdMethod.ReturnValue;
            if (createAndRetrieveIdPlaceholderValues == null) {
                lock (this) {
                    if (createAndRetrieveIdPlaceholderValues == null) {
                        createAndRetrieveIdPlaceholderValues = new Dictionary<InsertPlaceholder, string>();
                        createAndRetrieveIdPlaceholderValues.Add(InsertPlaceholder.AfterStatement, "; SELECT LAST_IDENTITY()");
                    }
                }
            }
            return createAndRetrieveIdPlaceholderValues;
        }
    }
}
