/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using OutSystems.HubEdition.Extensibility.Data.DMLService;

namespace OutSystems.HubEdition.DatabaseProvider.Cache.DML {

    /// <summary>
    /// Class that represents a contract for generating default values for simple queries.
    /// </summary>
    public class CacheDMLDefaultValues : BaseDMLDefaultValues {

        /// <summary>
        /// Initializes a new instance of the <see cref="CacheDMLDefaultValues"/> class.
        /// </summary>
        /// <param name="dmlService">The DML service.</param>
        internal CacheDMLDefaultValues(IDMLService dmlService) : base(dmlService) { }
    }
}
